### ISSUE TITLE
M2 13" Air??

### ISSUE THREAD

**Issue by BokBoy** [AsahiLinux/asahi-audio#13]
Hey, just reading the description, It said that M1 Air and M2 15" air was supported but there wasn't a mention about the M2 13". I presume that the 13" is supported because they share the same everything, but a read me change would be nice??

**Comment by Sojens** [comment]
There are likely quite a few Apple devices supported, however, I would assume that they aren't going to write down devices they haven't tested yet, and this software **isn't finished, or ready for consumer use**. Once the software has been developed to a point where testing devices is feasible, you will get an update.

FYI: You are reporting an issue on the currently unfinished **asahi-audio** GitHub project. Some people have commented on this one thinking it was for things like headphones, but AFAIK, this one is specifically for development of the built-in Mac speakers.

**Comment by BokBoy** [comment]
Nah yeah, I understand. It doesn't work for reference. When it comes out, I'll try it out. Thx for responding!
