### ISSUE TITLE
J313: EasyEffects breaks speakers

### ISSUE THREAD

**Issue by diamondburned** [AsahiLinux/asahi-audio#14]
Having EasyEffects running seems to break the `MacBook Air J313 Speakers` device completely, as shown by Carla:

![image](https://github.com/AsahiLinux/asahi-audio/assets/8463786/08cb4893-9664-47c2-9da7-852e762da9e9)

After stopping EasyEffects:

![image](https://github.com/AsahiLinux/asahi-audio/assets/8463786/e152baf8-5a7b-42fc-af23-ec4f34e6e7b0)

### Environment Info

- Distribution: [Nixpkgs@85f1ba3](https://github.com/NixOS/nixpkgs/tree/85f1ba3) except for Pipewire which comes from [Nixpkgs@b3460d2](https://github.com/NixOS/nixpkgs/tree/b3460d2)
- PipeWire version: 0.3.84
- Wireplumber version: 0.4.15 (with `policy-dsp` patch applied)
- Asahi Linux kernel version: asahi-6.5-15
- speakersafetyd is NOT running; I can't seem to get it to work

Otherwise, everything in [AsahiLinux/docs/wiki/SW:Speakers](https://github.com/AsahiLinux/docs/wiki/SW:Speakers/c0451576c804c79a7e49b54f357cab346bc4b9c0) is adhered to.

**Comment by ivabus** [comment]
As noted in SW:Speakers, you have to have the linux-asahi >= 6.5-25, maybe that's a thing.

**Comment by diamondburned** [comment]
Hmm, it's tracking the Arch PKGBUILD so I don't know if I should bump this one or the one in Asahi's.

**Comment by ivabus** [comment]
Maybe he should track [Fedora's COPR repo](https://copr.fedorainfracloud.org/coprs/g/asahi/kernel/) (or just wait until marcan tags the new kernel version, idk), as Fedora Asahi Remix becomes the distro.

**Comment by ivabus** [comment]
There is no reason to update PKGBUILDs for ALARM anymore

**Comment by diamondburned** [comment]
> Maybe it should track [Fedora's COPR repo](https://copr.fedorainfracloud.org/coprs/g/asahi/kernel/)

Is this available as a file anywhere? Similar to how PKGBUILD is a file?

**Comment by ivabus** [comment]
I think you should try to understand [SRPMs](https://download.copr.fedorainfracloud.org/results/@asahi/kernel/) but you could just try to update the version and commit hash to overwrite kernel with the newer rev and hash (of the tarball)

**Comment by diamondburned** [comment]
Newer kernel seems to fix speakersafetyd which also fixes this issue to an extent? This device below needs to be excluded, otherwise Easyeffects will keep stealing its output, but besides that, everything works fine!

![image](https://github.com/AsahiLinux/asahi-audio/assets/8463786/29f958d3-004d-40fa-912f-318918ae7971)
