### ISSUE TITLE
short "electric spark" sound when pausing or resuming audio media

### ISSUE THREAD

**Issue by kit-ty-kate** [AsahiLinux/asahi-audio#18]
When listening a to something (for example the spotify link in https://github.com/AsahiLinux/asahi-audio/issues/17) and pausing it, the majority of the time I get a slightly delayed (0.2s or something like that) "electric spark sound" slightly louder than the sound i just paused.
When i resume the song there is also a chance for a similar sound to happen again.

It's a bit difficult to describe sounds textually, but i suppose another description could be: "the sound you get when plugging/unplugging a 2.5mm audio jack on a live amp".

On the same machine, this behaviour doesn't exist on macOS.

Hardware: j316
Software:
- Linux 6.6.3-411.asahi.fc39.aarch64+16k
- asahi-audio 1.6

**Comment by chadmed** [comment]
This is a known bug with how Pipewire handles latency caused by DSP graphs. We are looking into it. It's not dangerous to the speakers or any other part of your machine, it's just annoying. We aim to have this fixed soon.
