### ISSUE TITLE
The minimum volume on j316 is too loud

### ISSUE THREAD

**Issue by kit-ty-kate** [AsahiLinux/asahi-audio#19]
I'm currently at the minimum volume on j316:
```
$ wpctl status
[...]
 ├─ Sinks:
 │  *   51. MacBook Pro J316 Speakers           [vol: 0.01]
[...]
```
one more `wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-` and it's complete silence.

That level is, I would say: "comfortable audio level during the day", however at night as things get quieter around this is an unreasonable audio level.

If i have to compare to macOS I would say this is comparable to at least a level 5 (1 being the quietest)

I know I can reduce the level of each applications further but this is rather tedious to do to each applications and rather annoying as they reset to the default audio level when the audio stream stops.

**Comment by chadmed** [comment]
Go to `/usr/share/asahi-audio/j316/graph.json` and play with the values under `capture.volumes`. They're in dB and control the base volume of the loudness compensator.

**Comment by kit-ty-kate** [comment]
Thanks! `-55.0` (was 42.5 before) seems to be a good default so far. I'll keep using it for a day and I'll open a PR if it's still good
