### ISSUE TITLE
Speakers shown as Macbook Pro J414 speakers after reboot

### ISSUE THREAD

**Issue by MGlants** [AsahiLinux/asahi-audio#20]
[asahi-diagnose-20231222-001907.txt](https://github.com/AsahiLinux/asahi-audio/files/13746227/asahi-diagnose-20231222-001907.txt)
Pipewire macaudio profile is "pro-audio
pro-audio".
Headphones and speakers will not work. Select the "Default" or "HiFi" profile

Is it okay, or i broke something

**Comment by chadmed** [comment]
That's what they're supposed to be called. Please delete `~/.local/state/wireplumber` then log out and log back in. Your setup should be fine after this.
