### ISSUE TITLE
j314: Max sound in linux is much quieter than in macos.

### ISSUE THREAD

**Issue by WhatAmISupposedToPutHere** [AsahiLinux/asahi-audio#23]
5-10% in macos is roughly equivalent to 50%-ish in linux, while 100% in linux is around 45%-ish. 
[asahi-diagnose-20231222-153309.txt.gz](https://github.com/AsahiLinux/asahi-audio/files/13753424/asahi-diagnose-20231222-153309.txt.gz)

**Comment by chadmed** [comment]
As per `#asahi-alt` logs, the issue here was our Wireplumber policy not setting the raw output volume to 100%. Setting it manually fixed this, however the policy still doesn't work. Leaving this open to hopefully document why this can happen and how to fix it.

**Comment by chadmed** [comment]
Seems to be fixed. Feel free to reopen if not.
