### ISSUE TITLE
Ardour DAW out of the box NUKES the nice Asahi sound stack on 2023 M2Pro mbp14

### ISSUE THREAD

**Issue by zenerve** [AsahiLinux/asahi-audio#30]
Sorry for the clickbaity-style title, it is intended as humour, and thanks for the fantastic work.

Step to reproduce: on clean, fresh, updated asahi-fedora-gnome installed through alx.sh:
- Check that pipewire/alsa, pipewire/pulse but _not_ pipewire/jack are installed (and asahi-audio, speakersafetyd, lv2-bandstown etc)
-> confirm all is by default settings, and everything works as intended.
- Install qpwgraph or helvum and ardour8 from the Fedora standard repos
- Have vlc or anything playing something at mid-level volume ; fire up your patch application to have a visual on the sound "plumbing" occurring, sending everything to the stereo input of the macbook speakers.
- Fire up Ardour

--> Boom ; On Ardour Splash Screen, before anything really happens, the sound will go to 100% and you can't lower it by the keyboard ; in your patch application you'll notice the loudspeakers "middleman" with the stereo input has disappeared, and everything seems to have six outputs and inputs. It is half-possible to make ardour work in alsa or pulse, but not nicely with other apps ; jack seems to crash and be impossible to use. Manually killing speakersafetyd cuts sound, but restarting it doesn't give us back control. If you keep on fiddling you'll end up with only "dummy output", and no sound, until you reboot.

--> My poorman's fix: install pipewire-jack-audio-connection-kit instead of jack-audio-connection-kit ; use ardour8 from Fedora and not Ardour from flatpak (both from Fedora and Flathub)

Should pipewire/jack be default, maybe? Am I the only crazie to do real soundtracks on Asahi?

My install was fresh from this afternoon, because I noticed, but didn't document, some misbehaviour after an unrelated reinstall of the fedora gnome remix ; thanks again for the hard work.

**Comment by chadmed** [comment]
Of course JACK DESTROYS Asahi audio with facts and logic. Only one can have the audio device open and JACK taking it will fold Pipewire/Wireplumber.

Your "poorman" fix is *the* fix. You have to use Pipewire's JACK implementation.

**Comment by zenerve** [comment]
Thanks. Modern Ardour uses Alsa by default tho, still knocks everything flat out. 

Should I report this elsewhere? Why is "Standard" Jack installed by default here? Why not Pipe-Jack?

**Comment by chadmed** [comment]
That would cause the same symptoms - only one application can actually have an ALSA device open at any given time. It's a major reason for the existence of sound servers in the first place.

In terms of Ardour relying on JACK instead of Pipewire's JACK implementation, that's probably a question for someone involved in packaging it for Fedora.

**Comment by chadmed** [comment]
Raised bug on RH Bugzilla:  https://bugzilla.redhat.com/show_bug.cgi?id=2262466

**Comment by chadmed** [comment]
Closing this as it seems like this is the expected behaviour upstream. Pipewire JACK will just have to be installed by Ardour users.
