### ISSUE TITLE
Help EQ or with some sort of guide.

### ISSUE THREAD

**Issue by RyanTheTide** [AsahiLinux/asahi-audio#31]
Hi there,

Was looking for some help regarding the EQ if you will. I understand that the vision for the project is to make the response as flat as possible. The audio is amazing for Linux (and likely more true to nature then Apple's own implementation) and this project has me even more excited to see how Asahi develops. I would however prefer the "smiley face" EQ that Apple has implemented just as personal preference. I have seen the Bankstown project mentioned and see it is pre-installed by default with my fresh install but have no way to know (I don't know anything about pipewire and lv2) if that's the solution to my issues and isn't enabled or if what I'm after simply isn't something the team wanted or if it's just not possible. I am moderately versed in understanding how the different subsystems interact and am getting back into daily driving on a desktop but am a complete amateur when it comes to audio (yet alone laptop audio) and how to hard code an EQ like what Apple has "OS-wide". Additionally I have noticed the audio to be louder while still clear so props to the team again, many thanks.

Treat me as an amateur in Fedora, preference has always been Arch followed by Debian (with a lack of any other main distros other then Android), this is my first proper stint into Fedora. Finally I prefer GNOME DE but if there are more audio settings available in KDE Plasma I will endeavor to give it a go for simplicity.

If possible a guide to this somewhere as well may be helpful to other users too.

Specs as followed:
Model - MacBook Pro 16" (M1 Pro) 2021
Kernel Ver - 6.6.3-413.asahi.fc39.aarch64+16k
OS - Fedora 39 Remix
DE - GNOME 45.3

**Comment by chadmed** [comment]
Messing with the Pipewire DSP properly requires special tooling (specifically a calibration mic and REW) and changing any of the parameters exposed in the JSON files will probably just result in a worse sound overall.

Use EasyEffects and pretend the Pipewire DSP simply doesn't exist.
