### ISSUE TITLE
Question about installation on arch arm

### ISSUE THREAD

**Issue by arthuradriaens-code** [AsahiLinux/asahi-audio#32]
Hello,

I installed asahi a while back on my MacBook Air (13-inch, M1, 2020) with arm arch on top as I'm used to arch. 
I know this isn't really the place to ask these types of questions but I'm unsure how I'd install asahi-audio, from what I see in other parts of the forum I get that you can install this as a package on fedora but this doesn't seem to be a thing
on arch, as neither speakersafetyd nor asahi-audio give any matches (I have asahi, core, extra, community, alarm and aur as sources).

Is there a source I'm missing or should I install this manually using the make core install (I have no experience with pipewire so I'm somewhat unsure of what to do after that).

Thanks in advance and  kind regards

**Comment by chadmed** [comment]
Maintenance on the Arch PKGBUILDs is effectively abandoned at this stage, so you will have to either move to Fedora Asahi Remix, one of the other alt distros, or build from source.

**Comment by mkurz** [comment]
@joske updated the Asahi ALARM packages and also set up the speakersafetyd and asahi-audio packages. You can find all those here:
- https://github.com/AsahiLinux/PKGBUILDs/pulls/joske

I still hope that marcan will update the Asahi ALARM packages in the "official" repos ([here](https://cdn.asahilinux.org/aarch64/)), at least he talked about it [here](https://social.treehouse.systems/@AsahiLinux/111607864744814408):
> Speaker support can only be added to distributions which, at this time, backport a critical lsp-plugins bugfix. ALARM at this time does not have it, so we can't enable speaker support yet.
> 
> That should finally be fixed later this month, so hopefully we can get things set up for ALARM in January. 
> ...

**Comment by chadmed** [comment]
Closing this as ALARM is mostly dead and buried, and this has nothing to do with `asahi-audio` proper
