### ISSUE TITLE
Unmute does not work

### ISSUE THREAD

**Issue by stevenae** [AsahiLinux/asahi-audio#34]
System details at end of post.

I press mute (keyboard) and audio mutes, GUI displays mute. I then press mute (keyboard) again and GUI displays volume level, but no sound comes out until I press volume up or down (keyboard).

Details:

Operating System: Fedora Linux Asahi Remix 39
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.6.3-413.asahi.fc39.aarch64+16k (64-bit)
Graphics Platform: Wayland
Processors: 4 × Apple Firestorm (M1), 4 × Apple Icestorm (M1)
Memory: 7.3 GiB of RAM
Graphics Processor: Apple M1
Product Name: Apple MacBook Air (M1, 2020)
U-Boot Version: 2023.07

**Comment by chadmed** [comment]
This is a side effect of how we map the equal loudness curve plugin to the channel volumes. I think this needs changes in Plasma's volume control module. It's something that's on the to-do list.

**Comment by stevenae** [comment]
Thank you for the update.

**Comment by chadmed** [comment]
Fixed in Plasma 6
