### ISSUE TITLE
Cannot unmute nor lower down volume (main branch)

### ISSUE THREAD

**Issue by mrkcee** [AsahiLinux/asahi-audio#36]
I am running a custom installation of openSUSE on my M1. I installed asahi-audio based on main branch because the wireplumber version on my system is 0.5.1.

I noticed that I cannot unmute nor lower down the volume of the speakers. It always gets unmuted or increased back to 100 when I try to mute or lower it respectively. Is this an intended behavior for now?

**Comment by chadmed** [comment]
No release was tagged, `main` is not ready yet. WirePlumber doesn't even have the API merged.

Please downgrade your WirePlumber to the last 0.4.x release and use the tagged v1.8 release of `asahi-audio` until a 2.0 release is tagged.

**Comment by mrkcee** [comment]
Got it. Thank you!
