### ISSUE TITLE
Gentoo asahi no suond J316 

### ISSUE THREAD

**Issue by chazy-chaz** [AsahiLinux/asahi-audio#40]
Hi
After installing gentoo asahi there is no sound in the speakers but there is sound in the headphones.
I reinstalled "asahi-audio pipewire wireplumber" several times, but it didn't help.
It's as if the sound on the speakers is zero.
![2024-05-04_18-35_1536x689](https://github.com/AsahiLinux/asahi-audio/assets/7883009/04cacb2c-23f3-4f69-8ee1-48cee6bebfb8)
![2024-05-04_15-11_1890x943](https://github.com/AsahiLinux/asahi-audio/assets/7883009/9bc32a9d-98ee-4c9e-b321-eab09d4f99b1)
![2024-05-04_15-06_1902x920](https://github.com/AsahiLinux/asahi-audio/assets/7883009/a9393e14-9ba1-4f64-bc1e-b325a0ba9570)
![2024-05-04_14-49_718x187](https://github.com/AsahiLinux/asahi-audio/assets/7883009/ef086c34-be7e-4535-a387-cde0d63c64b6)
![2024-05-04_15-13_1063x929](https://github.com/AsahiLinux/asahi-audio/assets/7883009/703ef8e5-73a1-4563-8f48-fe91a77c50e5)
![2024-05-04_15-06_942x294](https://github.com/AsahiLinux/asahi-audio/assets/7883009/86996aa5-2a8a-4687-baa3-082c9f54b3f0)
![2024-05-04_15-06_2590x1545](https://github.com/AsahiLinux/asahi-audio/assets/7883009/87bed794-0c9e-43af-88f7-64220736677d)
![2024-05-04_15-05_2574x852](https://github.com/AsahiLinux/asahi-audio/assets/7883009/c2888a01-4a1b-41e5-9973-94a856ad969e)
![2024-05-04_15-04_2575x1051](https://github.com/AsahiLinux/asahi-audio/assets/7883009/332c5482-0758-49ce-9a95-8f8d4198e3d5)

**Comment by chazy-chaz** [comment]
[Uploading asahi-diagnose-20240504-144942.txt…]()

**Comment by chadmed** [comment]
Have you started `speakersafetyd` and added it to your default runlevel?

**Comment by chazy-chaz** [comment]
no))
thank you kind man.
thank you for accompanying gentoo asahi.
