### ISSUE TITLE
Microphone doesnt work

### ISSUE THREAD

**Issue by yolanda2010** [AsahiLinux/asahi-audio#43]
I use Apple MacBook Air (M1, 2020),and the os ver is Remix39

When I use Audacity to record my voice,there is no sound.I have already install the dependence and try many times.

Oh how can I get logs about the aduio?(And My English Isnt Well ...)

**Comment by chadmed** [comment]
The microphones are not supported yet. See https://github.com/AsahiLinux/docs/wiki/M1-Series-Feature-Support, https://github.com/AsahiLinux/docs/wiki/M2-Series-Feature-Support and https://github.com/AsahiLinux/docs/wiki/M3-Series-Feature-Support
