### ISSUE TITLE
Question: How would I make my own DSP configuration for a Windows Laptop?

### ISSUE THREAD

**Issue by purrpurrn** [AsahiLinux/asahi-audio#45]
Is there any guide or is this even possible to improve the sound of my speakers?

**Comment by JuniorJPDJ** [comment]
I'm also interested. Would like to make Framework Laptop sound better and I've access to the radio calibration microphones and devices. Just need to know what I exactly need to play/record and how to use it.
Already configured bankstown and it's nice, but want to make it even better :D

**Comment by chadmed** [comment]
REW was used to measure the standard frequency response. EQ filters were then applied that flattened this response and then exported as an impulse response. The testing cycle is quite slow and it will require a few passes to get right, but it's not complicated if you have the equipment and skill to use it properly.

**Comment by RishabhBoop** [comment]
> Already configured bankstown and it's nice, but want to make it even better :D

Hey could you explain how you did that? I use Fedora 40 and installed the dnf package for the bankstown plugin and edited my `~/.config/pipewire/filter-chain.conf` as shown in https://www.reddit.com/r/linuxaudio/comments/197i1yh/pipewire_loading_an_lv2_bass_enhancer_plugin/. This however did not work for some reason. I would love to get it working on my Dell XPS 15, so it can finally sound more like it does on windows.

**Comment by JuniorJPDJ** [comment]
@RishabhBoop did you enable filter-chain service?
In Arch Linux it's being done like that:
`systemctl --user enable --now filter-chain.service`

This is my config file:

```
$ cat ~/.config/pipewire/filter-chain.conf.d/bankstown.conf
context.modules = [
  {
    name = libpipewire-module-filter-chain
    args = {
      "node.description": "Framework Speakers",
      "media.name": "Framework Speakers",
      "filter.graph": {
          "nodes": [
              {
                  "type": "lv2",
                  "plugin": "https://chadmed.au/bankstown",
                  "name": "bassex",
                  "control": {
                      "bypass": 0,
                      "amt": 1.5,
                      "sat_second": 1.3,
                      "sat_third": 2.5,
                      "blend": 1.0,
                      "ceil": 200.0,
                      "floor": 20.0,
                      "final_hp": 100.0
                  }
              }
          ],
          "inputs": [
              "bassex:in_l",
              "bassex:in_r"
          ],
          "outputs": [
              "bassex:out_l",
              "bassex:out_r"
          ],
      },
      "capture.props": {
          "node.name": "audio_effect.fwork-speakers",
          "media.class": "Audio/Sink",
          "audio.channels": "2",
          "audio.position": ["FL", "FR"],
          "audio.allowed-rates": [48000, 44100],
          "device.api": "dsp",
          "node.virtual": "false",
          "priority.session": 850,
          "state.default-channel-volume": 0.343,
          "device.icon-name": "audio-speakers"
      },
      "playback.props": {
          "node.name": "effect_output.fwork-speakers",
          "target.object": "alsa_output.pci-0000_00_1f.3.analog-stereo",
          "node.passive": "true",
          "audio.channels": "2",
          "audio.allowed-rates": [48000, 44100],
          "audio.position": ["FL", "FR"]
      }
    }
  }
]
```

You may need to tweak control values of bankstown, `media.name`, `node.description`, `node.name` and `target.object`.

**Comment by RishabhBoop** [comment]
Unfortunately the service is failing:
```
rishabh@xps-fedora:~$ systemctl --user status filter-chain.service
× filter-chain.service - PipeWire filter chain daemon
     Loaded: loaded (/usr/lib/systemd/user/filter-chain.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Fri 2024-09-06 19:18:46 CEST; 30s ago
   Duration: 11ms
    Process: 2207 ExecStart=/usr/bin/pipewire -c filter-chain.conf (code=exited, status=254)
   Main PID: 2207 (code=exited, status=254)
        CPU: 11ms

Sep 06 19:18:46 xps-fedora systemd[1735]: filter-chain.service: Scheduled restart job, restart counter is at 6.
Sep 06 19:18:46 xps-fedora systemd[1735]: filter-chain.service: Start request repeated too quickly.
Sep 06 19:18:46 xps-fedora systemd[1735]: filter-chain.service: Failed with result 'exit-code'.
Sep 06 19:18:46 xps-fedora systemd[1735]: Failed to start filter-chain.service - PipeWire filter chain daemon.

```
All I changed were `media.name`, `node.description`, `node.name` and `target.object`. 
Do I need to edit `filter-chain.conf` so that `libpipewire-module-filter-chain` loads ?

**Comment by RishabhBoop** [comment]
> REW was used to measure the standard frequency response. EQ filters were then applied that flattened this response and then exported as an impulse response. The testing cycle is quite slow and it will require a few passes to get right, but it's not complicated if you have the equipment and skill to use it properly.

This is probably a dumb question, but can I just use a phone microphone (e.g. pixel 7 microphone)  to measure the standard frequency response?
Do you guys have a script that automates the process of applying the EQ filters and then exporting?

**Comment by chadmed** [comment]
You ~must~ should use a proper calibration mic to do this, as a phone mic will absolutely not have a linear frequency response. Using a random mic that is not actually calibrated or designed for this work will introduce inaccuracies in your frequency response measurements, which will lead to you setting incorrect values in your EQ filters, which will ultimately lead to an inaccurate and poor sound quality.

And no, there are no scripts. There is a numpy/scipy tool in the repo that will trim your generated IRs, however. Everything in REW should be done manually as this is the only way to guarantee that your filters are actually correct. REW's automatic "predict filters from response" feature sucks even as a starting point and will just give you incorrect results.

Besides, when starting this there was no real way to automate REW. It now has a REST API that it exposes via its own dinky little HTTP server, but you have to pay for a REW licence to use it. REW is not libre/FOSS, much to my chagrin.

**Comment by chadmed** [comment]
It doesn't need to be {hemi,}anechoic, just very quiet.
