### ISSUE TITLE
Speaker audio picked up by microphone

### ISSUE THREAD

**Issue by SoyBrayM** [AsahiLinux/asahi-audio#46]
While using Microsoft Teams, since the i know the integrated microphone isn't currently supported, I left the mic open, and while waiting for the reunion to start I played a video on YouTube, but the audio not only came from the speakers, but also was going through the Teams mic.

I suspect that this is expected and is used for the speaker safety daemon since the device used for the mic is called "Monitor of MacBook Air J313 Speakers".

**Comment by chadmed** [comment]
speakersafetyd uses a hidden PCM to do its job. The loopback/monitor device you're seeing in Teams is created by WebRTC/Teams itself and is not caused by asahi-audio or speakersafetyd.
