### ISSUE TITLE
MBP M1 - Audio output gets disabled when I plug in a microphone

### ISSUE THREAD

**Issue by danberindei** [AsahiLinux/asahi-audio#51]
I believe this started when I did the F41 upgrade, but I'm not 100% sure.

kernel 6.11.6-401.asahi.fc41.aarch64+16k
alsa-ucm-asahi-5-4.fc41.noarch
asahi-audio-2.3-1.fc41.noarch
pipewire-1.2.6-1.fc41.aarch64
speakersafetyd-1.0.2-1.fc41.aarch64
wireplumber-0.5.5-2.fc41.aarch64

All I see with journalctl is
```
Nov 11 10:35:51 denulu-m1 kernel: cs42l84 2-004b: Plug event
Nov 11 10:35:51 denulu-m1 kernel: cs42l84 2-004b: Detected mic
Nov 11 10:35:51 denulu-m1 wireplumber[2579]: m-lua-scripting: <WpSpaPod:0xaaaadcb40990> Forcing Speaker route props: <WpDevice:0xaaaadc09b4c0>:
                                               Object: size 136, type Spa:Pod:Object:Param:Route (262153), id Spa:Enum:ParamId:Route (13)
                                                 Prop: key Spa:Pod:Object:Param:Route:props (10), flags 00000000
                                                   Object: size 64, type Spa:Pod:Object:Param:Props (262146), id Spa:Enum:ParamId:Route (13)
                                                     Prop: key Spa:Pod:Object:Param:Props:mute (65540), flags 00000000
                                                       Bool false
                                                     Prop: key Spa:Pod:Object:Param:Props:channelVolumes (65544), flags 00000000
                                                       Array: child.size 4, child.type Spa:Float
                                                         Float 1.000000
                                                 Prop: key Spa:Pod:Object:Param:Route:device (3), flags 00000000
                                                   Int 0
                                                 Prop: key Spa:Pod:Object:Param:Route:index (1), flags 00000000
                                                   Int 0
```

Audio output starts working again after I unplug the microphone, the journalctl output is similar:
```
Nov 11 10:35:58 denulu-m1 kernel: cs42l84 2-004b: Unplug event
Nov 11 10:35:58 denulu-m1 wireplumber[2579]: m-lua-scripting: <WpSpaPod:0xaaaadd71cef0> Forcing Speaker route props: <WpDevice:0xaaaadc09b4c0>:
                                               Object: size 136, type Spa:Pod:Object:Param:Route (262153), id Spa:Enum:ParamId:Route (13)
                                                 Prop: key Spa:Pod:Object:Param:Route:props (10), flags 00000000
                                                   Object: size 64, type Spa:Pod:Object:Param:Props (262146), id Spa:Enum:ParamId:Route (13)
                                                     Prop: key Spa:Pod:Object:Param:Props:mute (65540), flags 00000000
                                                       Bool false
                                                     Prop: key Spa:Pod:Object:Param:Props:channelVolumes (65544), flags 00000000
                                                       Array: child.size 4, child.type Spa:Float
                                                         Float 1.000000
                                                 Prop: key Spa:Pod:Object:Param:Route:device (3), flags 00000000
                                                   Int 0
                                                 Prop: key Spa:Pod:Object:Param:Route:index (1), flags 00000000
                                                   Int 0
Nov 11 10:35:58 denulu-m1 gsd-media-keys[2783]: Unable to get default source
```

I've included screenshots from coppwr and the output of `pw-cli info all` with and without the mic plugged in.

![without mic 2024-11-11 10-43-13](https://github.com/user-attachments/assets/4d2cc676-9016-4ba9-9622-ef0b7ba2bdc8)
![with mic 2024-11-11 10-41-55](https://github.com/user-attachments/assets/ceb2384a-9ea7-492e-b421-acbff788582b)
[pw-cli-info-all-with-mic.txt](https://github.com/user-attachments/files/17699754/pw-cli-info-all-with-mic.txt)
[pw-cli-info-all-without-mic.txt](https://github.com/user-attachments/files/17699755/pw-cli-info-all-without-mic.txt)

[asahi-diagnose-20241111-102927.txt](https://github.com/user-attachments/files/17699489/asahi-diagnose-20241111-102927.txt)

**Comment by chadmed** [comment]
The headset codec does not support raw mics and will set up a raw mic as a pair of headphones or a headset depending on certain things.

This particular issue though is related to the fact that the target nodes specified in asahi-audio 2.3 do not exist. This _should_ be fixed with asahi-audio 2.4, so once that lands in Fedora repos give it a test and let me know.

**Comment by danberindei** [comment]
I have also tried my bluetooth headphones and journalctl shows some logs from Gnome/systemd-logind/input-remapper trying to do something with the headphones buttons, but nothing from pipewire/wireplumber.

```
Nov 11 11:06:56 denulu-m1 kernel: input: WH-CH720N (AVRCP) as /devices/virtual/input/input9
Nov 11 11:06:56 denulu-m1 gsd-media-keys[2783]: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
Nov 11 11:06:56 denulu-m1 gsd-media-keys[2783]: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
Nov 11 11:06:56 denulu-m1 gsd-media-keys[2783]: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
Nov 11 11:06:56 denulu-m1 gsd-media-keys[2783]: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
Nov 11 11:06:56 denulu-m1 wireplumber[25877]: spa.bluez5.native: RFCOMM receive command but modem not available: AT+NREC=0
Nov 11 11:06:56 denulu-m1 wireplumber[25877]: spa.bluez5.native: RFCOMM receive command but modem not available: AT+XAPL=0x054C-0x0EAF-0108,2
Nov 11 11:06:56 denulu-m1 (udev-worker)[28851]: input9: Process '/bin/input-remapper-control --command autoload --device ' failed with exit code 2.
Nov 11 11:06:56 denulu-m1 input-remapper-service[973]: Request to autoload for "WH-CH720N (AVRCP)"
Nov 11 11:06:56 denulu-m1 input-remapper-service[973]: Found "Apple Internal Keyboard / Trackpad", "Apple Internal Keyboard / Trackpad 2", "Apple SMC power/lid events", "input-remapper keyboard", "input-remapper Apple Internal Keyboard / Trackpad forwarded", "WH-CH720N (AVRCP)"
Nov 11 11:06:56 denulu-m1 systemd-logind[984]: Watching system buttons on /dev/input/event6 (WH-CH720N (AVRCP))
```

Both coppwr and Gnome Settings say the audio output should be going only to the internal speakers, but instead I can hear a very faint version of the audio I'm trying to play in the headphones.
![with headphones 2024-11-11 11-18-51](https://github.com/user-attachments/assets/5ddd4eb6-6af7-4d6e-9606-29bbde4273d9)

[pw-cli-info-all-with-headphones.txt](https://github.com/user-attachments/files/17700076/pw-cli-info-all-with-headphones.txt)

When I plugged in the mic while connected to the Bluetooth headphones, wireplumber crashed:
https://bugzilla.redhat.com/show_bug.cgi?id=2325139

**Comment by chadmed** [comment]
No, that is not possible. We don't touch the signal path on the 3.5mm jack at all.

**Comment by danberindei** [comment]
I went back to the Gnome Settings later and the microphone volume was about 15%, that explains why the recording volume was so low. Perhaps it didn't properly handle the notification when the Bluetooth headphones input was replaced by the Built-in audio input, and that's why it was showing me the microphone volume at 100% earlier.

Thanks again @chadmed!
