### ISSUE TITLE
 Changing the volume plays previous audio from YouTube after paused

### ISSUE THREAD

**Issue by m1m1k4tz** [AsahiLinux/asahi-audio#54]
# Steps to reproduce
* 1. Pause a YouTube video
* 2. Change the volume 

This should play a snippet from the video

**Comment by chadmed** [comment]
This is an issue with PipeWire/WirePlumber. The DSP graph is suspended before its buffers are totally emptied. When the graph is restarted, its buffers are flushed out and you get whatever was left in the buffer when it was suspended. Please report it upstream.
